### ISSUE TITLE
cannot read property '0' of undefined

### ISSUE THREAD

**Issue by mentaluproar** [Tommrodrigues/homebridge-web-rgb#1]
I can't get homebridge to start with this plugin installed.  I get the following error:
```
[10/25/2019, 1:28:29 AM] TypeError: Cannot read property '0' of undefined
    at HTTP_RGB.<anonymous> (/usr/lib/node_modules/homebridge-web-rgb/index.js:106:28)
    at Request._callback (/usr/lib/node_modules/homebridge-web-rgb/index.js:89:7)
    at Request.self.callback (/usr/lib/node_modules/homebridge-web-rgb/node_modules/request/request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-web-rgb/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:210:5)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-web-rgb/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:299:28)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

my config.json contains...
```
    "accessories": [
        {
            "accessory": "HTTP-RGB",
            "name": "Covfefe Table",
            "apiroute": "http://10.0.1.42/json"
        }
    ],
```

**Comment by phenotypic** [comment]
Hi there, I think the problem is what you have specified in your `config.json` for `apiroute`. Please refer to the `API Interfacing` section of the README. 

When the plugin polls the device, it takes what you have specified in `apiroute` and appends `/status` to it. In this case, it is requesting `http://10.0.1.42/json/status`. 

I think the easiest solution would be to change `apiroute` to `http://10.0.1.42` and then change the code on the RGB accessory such that the JSON is returned when `/status` is requested instead of `/json`.
